function (require, module, exports) {
    "use strict";

    // Unregisters this module from the global Cocos Creator module registry.
    // The module ID "8e79aRU2sNFmq3nZgboNd91" and the name "auto_play_blink" are used for internal tracking.
    cc._RF.push(module, "8e79aRU2sNFmq3nZgboNd91", "auto_play_blink");

    // Helper function for JavaScript class inheritance, often generated by TypeScript.
    // 'childClass' extends 'parentClass'.
    var __extends = (this && this.__extends) || (function () {
        var extendStatics = function (child, parent) {
            extendStatics = Object.setPrototypeOf ||
                ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
                function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
            return extendStatics(child, parent);
        };
        return function (d, b) {
            if (typeof b !== "function" && b !== null)
                throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
            extendStatics(d, b);
            function __() { this.constructor = d; }
            d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
        };
    })();

    // Helper function to apply decorators to classes and their members, common in TypeScript/Cocos Creator.
    // Used for @ccclass and @property.
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
        else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
        return c > 3 && r && Object.defineProperty(target, key, r), r;
    };

    // Mark this module as an ES module to enable 'import' functionality.
    Object.defineProperty(exports, "__esModule", { value: true });

    // Import the 'api' module from the specified path.
    // This allows access to functions like API.forbid_blink.
    var apiModule = require("./api/api");

    // Shorthand for Cocos Creator's decorator system.
    var ccDecorators = cc._decorator;
    var ccclass = ccDecorators.ccclass; // Decorator to register a class as a Cocos Creator component.
    // 'property' is imported but not used directly in this snippet, likely for other properties
    // that might have been removed during minification or are implicit.
    var property = ccDecorators.property;

    // Define the AutoPlayBlink class, which extends cc.Component.
    // This component is likely responsible for making a node (e.g., a guide or a hint) blink automatically.
    var AutoPlayBlink = (function (_super) {
        // Constructor for the AutoPlayBlink component.
        function AutoPlayBlink() {
            // Call the parent class (cc.Component) constructor.
            return _super.apply(this, arguments) || this;
        }

        // Apply inheritance: AutoPlayBlink extends cc.Component.
        __extends(AutoPlayBlink, _super);

        // Cocos Creator lifecycle method: called when the component is first initialized or enabled.
        AutoPlayBlink.prototype.onLoad = function () {
            // Get the cc.Animation component attached to the same node as this script.
            var animationComponent = this.node.getComponent(cc.Animation);

            // Check if an animation component exists and if the API.forbid_blink flag is false.
            // If both conditions are met, play the animation.
            if (cc.isValid(animationComponent) && !apiModule.API.forbid_blink) {
                animationComponent.play();
            }
        };

        // Apply the @ccclass decorator to register this class as a component in Cocos Creator.
        __decorate([ccclass], AutoPlayBlink);

        return AutoPlayBlink;
    })(cc.Component); // The AutoPlayBlink class extends cc.Component.

    // Set the default export of this module to the AutoPlayBlink class.
    exports.default = AutoPlayBlink;

    // Pops the module off the internal Cocos Creator module stack, indicating it's done loading.
    cc._RF.pop();
}