function (require, module, exports) {
    "use strict";

    // Unregisters this module from the global Cocos Creator module registry.
    // The module ID "fdfebGcfGBIAJyUrSoA6YCT" and the name "blink_2" are for internal tracking.
    cc._RF.push(module, "fdfebGcfGBIAJyUrSoA6YCT", "blink_2");

    // Helper function for JavaScript class inheritance, often generated by TypeScript.
    var __extends = (this && this.__extends) || (function () {
        var extendStatics = function (child, parent) {
            extendStatics = Object.setPrototypeOf ||
                ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
                function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
            return extendStatics(child, parent);
        };
        return function (d, b) {
            if (typeof b !== "function" && b !== null)
                throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
            extendStatics(d, b);
            function __() { this.constructor = d; }
            d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
        };
    })();

    // Helper function to apply decorators to classes and their members, common in TypeScript/Cocos Creator.
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
        else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
        return c > 3 && r && Object.defineProperty(target, key, r), r;
    };

    // Mark this module as an ES module.
    Object.defineProperty(exports, "__esModule", { value: true });

    // Imports the control module.
    var controlModule = require("./control");
    var ccDecorators = cc._decorator;
    var ccclass = ccDecorators.ccclass; // Decorator to register a class as a Cocos Creator component.
    var property = ccDecorators.property; // Decorator to expose properties in the editor.

    // A simple Cocos Creator component for playing a sound.
    var BlinkSoundPlayer = (function (_super) {
        // Constructor, initializes the blink_audio property.
        function BlinkSoundPlayer() {
            var _this = _super.apply(this, arguments) || this;
            _this.blink_audio = null;
            return _this;
        }

        // Apply inheritance: BlinkSoundPlayer extends cc.Component.
        __extends(BlinkSoundPlayer, _super);

        // Plays the audio clip assigned to this component.
        BlinkSoundPlayer.prototype.playAudio = function () {
            this.control = controlModule.control;
            this.control.playAudio(this.blink_audio, false);
        };

        // Apply @property decorators to expose the audio clip property in the editor.
        __decorate([property(cc.AudioClip)], BlinkSoundPlayer.prototype, "blink_audio", void 0);
        __decorate([ccclass], BlinkSoundPlayer);

        return BlinkSoundPlayer;
    })(cc.Component);

    // Set the default export of this module to the BlinkSoundPlayer class.
    exports.default = BlinkSoundPlayer;

    // Pops the module off the internal Cocos Creator module stack.
    cc._RF.pop();
}