function (require, module, exports) {
    "use strict";

    // Unregisters this module from the global Cocos Creator module registry.
    // The module ID "f83d5CyuapJcLAo4Xuab05M" and the name "prgs" are for internal tracking.
    cc._RF.push(module, "f83d5CyuapJcLAo4Xuab05M", "prgs");

    // Helper function for JavaScript class inheritance, often generated by TypeScript.
    // 'childClass' extends 'parentClass'.
    var __extends = (this && this.__extends) || (function () {
        var extendStatics = function (child, parent) {
            extendStatics = Object.setPrototypeOf ||
                ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
                function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
            return extendStatics(child, parent);
        };
        return function (d, b) {
            if (typeof b !== "function" && b !== null)
                throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
            extendStatics(d, b);
            function __() { this.constructor = d; }
            d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
        };
    })();

    // Helper function to apply decorators to classes and their members, common in TypeScript/Cocos Creator.
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
        else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || c;
        return c > 3 && r && Object.defineProperty(target, key, r), r;
    };

    // Mark this module as an ES module.
    Object.defineProperty(exports, "__esModule", { value: true });

    // Shorthand for Cocos Creator's decorator system.
    var ccDecorators = cc._decorator;
    var ccclass = ccDecorators.ccclass; // Decorator to register a class as a Cocos Creator component.
    var property = ccDecorators.property; // Decorator to expose properties in the editor.

    /**
     * Cocos Creator component for a progress bar.
     * This component simply holds a reference to a `cc.ProgressBar` node,
     * allowing it to be controlled by other scripts or the Cocos Creator editor.
     * The name "prgs" is likely short for "progress".
     */
    var ProgressBarComponent = (function (_super) {
        // Constructor, initializes component properties.
        function ProgressBarComponent() {
            var _this = _super.apply(this, arguments) || this;
            _this.progressBar = null; // Property to hold the cc.ProgressBar component.
            return _this;
        }

        // Apply inheritance: ProgressBarComponent extends cc.Component.
        __extends(ProgressBarComponent, _super);

        // Apply @property decorator to expose the 'progressBar' property in the editor.
        __decorate([property(cc.ProgressBar)], ProgressBarComponent.prototype, "progressBar", void 0);
        // Apply @ccclass decorator to register this class as a Cocos Creator component.
        __decorate([ccclass], ProgressBarComponent);

        return ProgressBarComponent;
    })(cc.Component); // The ProgressBarComponent class extends cc.Component.

    // Set the default export of this module to the ProgressBarComponent class.
    exports.default = ProgressBarComponent;

    // Pops the module off the internal Cocos Creator module stack, indicating it's done loading.
    cc._RF.pop();
}